<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.appturismo.show.backend.infrastructure.driverapaters</groupId>
		<artifactId>driverapaters</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<groupId>com.appturismo.show.backend.infrastructure.driverapaters.oracleadapter</groupId>
	<artifactId>oracleadapter</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>oracleadapter</name>
	<packaging>jar</packaging>
	<description>Módulo que agrupa los adaptadores técnicos de salida del sistema.</description>

	<dependencies>
		<dependency>
			<groupId>com.appturismo.show.backend.domain.model</groupId>
			<artifactId>model</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>com.oracle.database.jdbc</groupId>
			<artifactId>ojdbc11</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- JUnit 5 -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- Mockito core (@Mock, @InjectMocks, when, verify, etc.) -->
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- Mockito + JUnit 5 integration (@ExtendWith(MockitoExtension.class)) -->
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- MapStruct (API) -->
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
		</dependency>




	</dependencies>



</project>
