<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.appturismo.show.backend</groupId>
        <artifactId>backend</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <groupId>com.appturismo.show.backend.domain</groupId>
    <artifactId>domain</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>domain</name>
    <packaging>pom</packaging>
    <description>Módulo que encapsula el dominio y las reglas de negocio de la aplicación.</description>

<modules>
    <module>model</module>
    <module>usecase</module>
</modules>
</project>
